"""custom widgets

Revision ID: 46cf622fcac8
Revises: ef39ed611b58
Create Date: 2026-08-12 00:50:07.265479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46cf622fcac8'
down_revision: Union[str, Sequence[str], None] = 'ef39ed611b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('visualization', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_widget_name'), 'custom_widget', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_widget_name'), table_name='custom_widget')
    op.drop_table('custom_widget')
    # ### end Alembic commands ###
