"""initial schema

Revision ID: ed42a62fa85f
Revises: 
Create Date: 2026-08-10 20:47:34.862097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed42a62fa85f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_category'), 'exercise', ['category'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('workout',
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_performed_on'), 'workout', ['performed_on'], unique=False)
    op.create_table('set_entry',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('set_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_entry_exercise_id'), 'set_entry', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_entry_workout_id'), 'set_entry', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_entry_workout_id'), table_name='set_entry')
    op.drop_index(op.f('ix_set_entry_exercise_id'), table_name='set_entry')
    op.drop_table('set_entry')
    op.drop_index(op.f('ix_workout_performed_on'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_category'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
